CREATE TABLE `abastecimentos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`empresaId` int NOT NULL,
	`veiculoId` int NOT NULL,
	`motoristaId` int,
	`data` date NOT NULL,
	`tipoCombustivel` enum('diesel','arla','gasolina','etanol','gas','outro') NOT NULL,
	`quantidade` decimal(8,3) NOT NULL,
	`valorUnitario` decimal(8,3),
	`valorTotal` decimal(10,2),
	`kmAtual` int,
	`kmRodado` int,
	`mediaConsumo` decimal(5,2),
	`local` varchar(255),
	`tipoAbastecimento` enum('interno','externo') DEFAULT 'interno',
	`notaFiscal` varchar(50),
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	`deletedBy` int,
	`deleteReason` text,
	CONSTRAINT `abastecimentos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `acidentes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`empresaId` int NOT NULL,
	`veiculoId` int NOT NULL,
	`motoristaId` int,
	`data` date NOT NULL,
	`local` varchar(255),
	`descricao` text NOT NULL,
	`boletimOcorrencia` varchar(50),
	`valorDano` decimal(10,2),
	`status` enum('aberto','em_reparo','resolvido') NOT NULL DEFAULT 'aberto',
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	`deletedBy` int,
	`deleteReason` text,
	CONSTRAINT `acidentes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `adiantamentos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`empresaId` int NOT NULL,
	`funcionarioId` int NOT NULL,
	`viagemId` int,
	`valor` decimal(10,2) NOT NULL,
	`formaPagamento` enum('dinheiro','pix','transferencia','cartao') NOT NULL,
	`data` date NOT NULL,
	`status` enum('pendente','acertado','cancelado') NOT NULL DEFAULT 'pendente',
	`valorAcertado` decimal(10,2),
	`dataAcerto` date,
	`saldo` decimal(10,2),
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	`deletedBy` int,
	`deleteReason` text,
	CONSTRAINT `adiantamentos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `audit_log` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`empresaId` int,
	`userId` int NOT NULL,
	`userName` varchar(255),
	`acao` varchar(50) NOT NULL,
	`tabela` varchar(100) NOT NULL,
	`registroId` int NOT NULL,
	`dadosAntes` text,
	`dadosDepois` text,
	`ip` varchar(45),
	`userAgent` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `audit_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `checklists` (
	`id` int AUTO_INCREMENT NOT NULL,
	`empresaId` int NOT NULL,
	`veiculoId` int NOT NULL,
	`cavaloPrincipalId` int,
	`motoristaId` int,
	`turno` enum('manha','tarde','noite'),
	`tipo` enum('saida','retorno') NOT NULL DEFAULT 'retorno',
	`cracha` enum('conforme','nao_conforme','na'),
	`cnh` enum('conforme','nao_conforme','na'),
	`documentosVeiculo` enum('conforme','nao_conforme','na'),
	`epi` enum('conforme','nao_conforme','na'),
	`computadorBordo` enum('conforme','nao_conforme','na'),
	`cinto` enum('conforme','nao_conforme','na'),
	`banco` enum('conforme','nao_conforme','na'),
	`direcao` enum('conforme','nao_conforme','na'),
	`luzesPainel` enum('conforme','nao_conforme','na'),
	`tacografo` enum('conforme','nao_conforme','na'),
	`extintor` enum('conforme','nao_conforme','na'),
	`portas` enum('conforme','nao_conforme','na'),
	`limpador` enum('conforme','nao_conforme','na'),
	`buzina` enum('conforme','nao_conforme','na'),
	`freioDeMao` enum('conforme','nao_conforme','na'),
	`alarmeCacamba` enum('conforme','nao_conforme','na'),
	`cabineLimpa` enum('conforme','nao_conforme','na'),
	`objetosSoltos` enum('conforme','nao_conforme','na'),
	`pneus` enum('conforme','nao_conforme','na'),
	`vazamentos` enum('conforme','nao_conforme','na'),
	`trianguloCones` enum('conforme','nao_conforme','na'),
	`espelhos` enum('conforme','nao_conforme','na'),
	`lonaCarga` enum('conforme','nao_conforme','na'),
	`faixasRefletivas` enum('conforme','nao_conforme','na'),
	`luzesLaterais` enum('conforme','nao_conforme','na'),
	`luzesFreio` enum('conforme','nao_conforme','na'),
	`farol` enum('conforme','nao_conforme','na'),
	`piscaAlerta` enum('conforme','nao_conforme','na'),
	`re` enum('conforme','nao_conforme','na'),
	`setas` enum('conforme','nao_conforme','na'),
	`macacoEstepe` enum('conforme','nao_conforme','na'),
	`lanternas` enum('conforme','nao_conforme','na'),
	`itensNaoConformes` int DEFAULT 0,
	`observacoes` text,
	`assinaturaMotorista` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	`deletedBy` int,
	`deleteReason` text,
	CONSTRAINT `checklists_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contas_pagar` (
	`id` int AUTO_INCREMENT NOT NULL,
	`empresaId` int NOT NULL,
	`descricao` text NOT NULL,
	`categoria` enum('combustivel','manutencao','salario','freelancer','pedagio','seguro','ipva','licenciamento','pneu','outro') NOT NULL,
	`valor` decimal(10,2) NOT NULL,
	`dataVencimento` date NOT NULL,
	`dataPagamento` date,
	`status` enum('pendente','pago','vencido','cancelado') NOT NULL DEFAULT 'pendente',
	`fornecedor` varchar(255),
	`notaFiscal` varchar(50),
	`veiculoId` int,
	`funcionarioId` int,
	`viagemId` int,
	`comprovante` text,
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	`deletedBy` int,
	`deleteReason` text,
	CONSTRAINT `contas_pagar_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contas_receber` (
	`id` int AUTO_INCREMENT NOT NULL,
	`empresaId` int NOT NULL,
	`descricao` text NOT NULL,
	`categoria` enum('frete','cte','devolucao','outro') NOT NULL,
	`valor` decimal(10,2) NOT NULL,
	`dataVencimento` date NOT NULL,
	`dataRecebimento` date,
	`status` enum('pendente','recebido','vencido','cancelado') NOT NULL DEFAULT 'pendente',
	`cliente` varchar(255),
	`notaFiscal` varchar(50),
	`cteNumero` varchar(50),
	`viagemId` int,
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	`deletedBy` int,
	`deleteReason` text,
	CONSTRAINT `contas_receber_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `controle_tanque` (
	`id` int AUTO_INCREMENT NOT NULL,
	`empresaId` int NOT NULL,
	`tipo` enum('diesel','arla') NOT NULL,
	`data` date NOT NULL,
	`operacao` enum('entrada','saida') NOT NULL,
	`quantidade` decimal(8,3) NOT NULL,
	`valorUnitario` decimal(8,3),
	`valorTotal` decimal(10,2),
	`fornecedor` varchar(255),
	`notaFiscal` varchar(50),
	`veiculoId` int,
	`motoristaId` int,
	`saldoAnterior` decimal(8,3),
	`saldoAtual` decimal(8,3),
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`deletedAt` timestamp,
	`deletedBy` int,
	`deleteReason` text,
	CONSTRAINT `controle_tanque_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `despesas_viagem` (
	`id` int AUTO_INCREMENT NOT NULL,
	`viagemId` int NOT NULL,
	`empresaId` int NOT NULL,
	`tipo` enum('combustivel','pedagio','borracharia','estacionamento','oficina','telefone','descarga','diaria','alimentacao','outro') NOT NULL,
	`descricao` text,
	`valor` decimal(10,2) NOT NULL,
	`data` date,
	`comprovante` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`deletedAt` timestamp,
	`deletedBy` int,
	`deleteReason` text,
	CONSTRAINT `despesas_viagem_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `empresas` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nome` varchar(255) NOT NULL,
	`cnpj` varchar(18),
	`telefone` varchar(20),
	`email` varchar(320),
	`endereco` text,
	`cidade` varchar(100),
	`estado` varchar(2),
	`ativo` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	`deletedBy` int,
	`deleteReason` text,
	CONSTRAINT `empresas_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `funcionarios` (
	`id` int AUTO_INCREMENT NOT NULL,
	`empresaId` int NOT NULL,
	`nome` varchar(255) NOT NULL,
	`cpf` varchar(14),
	`rg` varchar(20),
	`telefone` varchar(20),
	`email` varchar(320),
	`funcao` enum('motorista','ajudante','despachante','gerente','admin','outro') NOT NULL,
	`tipoContrato` enum('clt','freelancer','terceirizado','estagiario') NOT NULL,
	`salario` decimal(10,2),
	`dataAdmissao` date,
	`dataDemissao` date,
	`valorDiaria` decimal(10,2),
	`valorMensal` decimal(10,2),
	`tipoCobranca` enum('diaria','mensal','por_viagem'),
	`dataInicioContrato` date,
	`dataFimContrato` date,
	`diaPagamento` int,
	`cnh` varchar(20),
	`categoriaCnh` varchar(5),
	`vencimentoCnh` date,
	`mopp` boolean DEFAULT false,
	`vencimentoMopp` date,
	`vencimentoAso` date,
	`banco` varchar(100),
	`agencia` varchar(10),
	`conta` varchar(20),
	`tipoConta` enum('corrente','poupanca','pix'),
	`chavePix` varchar(255),
	`observacoes` text,
	`foto` text,
	`ativo` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	`deletedBy` int,
	`deleteReason` text,
	CONSTRAINT `funcionarios_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `manutencoes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`empresaId` int NOT NULL,
	`veiculoId` int NOT NULL,
	`data` date NOT NULL,
	`tipo` enum('preventiva','corretiva','revisao','pneu','eletrica','funilaria','outro') NOT NULL,
	`descricao` text NOT NULL,
	`empresa` varchar(255),
	`valor` decimal(10,2),
	`kmAtual` int,
	`proximaManutencaoKm` int,
	`proximaManutencaoData` date,
	`notaFiscal` varchar(50),
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	`deletedBy` int,
	`deleteReason` text,
	CONSTRAINT `manutencoes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`loginMethod` varchar(64),
	`role` enum('user','admin','master_admin','monitor','dispatcher') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);
--> statement-breakpoint
CREATE TABLE `veiculos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`empresaId` int NOT NULL,
	`placa` varchar(10) NOT NULL,
	`tipo` enum('van','toco','truck','cavalo','carreta','empilhadeira','paletera','outro') NOT NULL,
	`cavaloPrincipalId` int,
	`marca` varchar(100),
	`modelo` varchar(100),
	`ano` int,
	`cor` varchar(50),
	`renavam` varchar(20),
	`chassi` varchar(30),
	`capacidadeCarga` decimal(8,2),
	`motoristaId` int,
	`ajudanteId` int,
	`kmAtual` int,
	`mediaConsumo` decimal(5,2),
	`vencimentoCrlv` date,
	`vencimentoSeguro` date,
	`classificacao` int DEFAULT 0,
	`observacoes` text,
	`ativo` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	`deletedBy` int,
	`deleteReason` text,
	CONSTRAINT `veiculos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `viagens` (
	`id` int AUTO_INCREMENT NOT NULL,
	`empresaId` int NOT NULL,
	`veiculoId` int NOT NULL,
	`cavaloPrincipalId` int,
	`motoristaId` int,
	`ajudante1Id` int,
	`ajudante2Id` int,
	`ajudante3Id` int,
	`origem` varchar(255),
	`destino` varchar(255),
	`dataSaida` timestamp,
	`dataChegada` timestamp,
	`kmSaida` int,
	`kmChegada` int,
	`kmRodado` int,
	`descricaoCarga` text,
	`pesoCarga` decimal(8,2),
	`freteTotalIda` decimal(10,2),
	`freteTotalVolta` decimal(10,2),
	`freteTotal` decimal(10,2),
	`adiantamento` decimal(10,2),
	`saldoViagem` decimal(10,2),
	`totalDespesas` decimal(10,2),
	`mediaConsumo` decimal(5,2),
	`status` enum('planejada','em_andamento','concluida','cancelada') NOT NULL DEFAULT 'planejada',
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	`deletedBy` int,
	`deleteReason` text,
	CONSTRAINT `viagens_id` PRIMARY KEY(`id`)
);
